services:

  ssh_tunnel:
    image: lscr.io/linuxserver/openssh-server:latest
    links:
      - mysql
      - postgres
    ports:
      - 10022:2222
    volumes:
      - ./data/ssh_tunnel/sshd_config.conf:/config/ssh_host_keys/sshd_config.d/torqle.conf
    environment:
      # enable root login with optional password
      SUDO_ACCESS: true
      PASSWORD_ACCESS: true
      USER_NAME: torqle
      USER_PASSWORD: littlebuddy
    

  mysql:
    image: bitnami/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      SQL_MODE: ""
      MYSQL_DATABASE: testdb

  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: pguser
      POSTGRESQL_PASSWORD: mypassword
      POSTGRESQL_DATABASE: testdb

  mongo:
    image: mongo
    ports:
      - 27017:27017

networks:
  torqle:
    external: true
